import { Poppins, Ubuntu, Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const pop = Inter({ subsets: ["latin"]});

export const metadata = {
  title: "To Do",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pop.className}>
        <Header />
        {children}
				<Footer />
      </body>
    </html>
  );
}
